port: :8082
gorm:
  migrate:
    drop: true
  sqlite:
    path: data.db
  mysql:
    host: 127.0.0.1
    user: root
    password: 123456tim
    database: selfman

gin:
  static:
    path: static
    ftp: true
upload:
  image:
    dir: upload/image/
    path: /s/img/